
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      channel: stable
      target: x86_64-unknown-linux-gnu
    # - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    #   channel: stable
    #   target: i686-unknown-linux-gnu

install:
  - cmd: appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - cmd: rustup-init -yv --default-toolchain %channel% --default-host %target%
  - cmd: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - sh: curl https://sh.rustup.rs -sSf -o rustup-init
  - sh: chmod +x rustup-init
  - sh: ./rustup-init -y --default-toolchain $channel --default-host $target 
  - sh: export PATH=$PATH:$HOME/.rustup/toolchains/$channel-$target/bin
  - sh: export PATH=$PATH:$HOME/.cargo/.bin
  - rustc -vV
  - cargo -vV

test_script:
  - cargo test --verbose

build_script:
  - cargo build --release

after_build:
  - cmd: 7z a ddex-%target%.zip %APPVEYOR_BUILD_FOLDER%\target\release\ddex.exe
  - cmd: appveyor PushArtifact -Path ddex-%target%.zip -DeploymentName %target%
  - sh: 7z a ddex-$target.zip $APPVEYOR_BUILD_FOLDER/target/release/ddex
  - sh: appveyor PushArtifact -Path ddex-$target.zip -DeploymentName $target
