
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      channel: stable
      target: x86_64-unknown-linux-gnu
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      channel: stable
      target: i686-unknown-linux-gnu

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --verbose